steps:
    # Build the container image
   - name: 'gcr.io/cloud-builders/dokcer'
     args: ['build', '-t', 'gcr.io/dtu-mlops-374314/trainer:latest', './trainer.dockerfile']
   # Push the container image to Container Registry
   - name: 'gcr.io/cloud-builders/dokcer'
     args: ['push', 'gcr.io/dtu-mlops-374314/trainer:latest']