steps:
    # Build the container image.
   - name: 'gcr.io/cloud-builders/docker' # pre-defined builder
     args: ['build', '-t', 'gcr.io/dtu-mlops-374314/train-img:latest', '.'] # arguments to the builder
   # Push the container image to Container Registry
   - name: 'gcr.io/cloud-builders/docker' # pre-defined builder
     args: ['push', 'gcr.io/dtu-mlops-374314/train-img:latest'] # arguments to the builder