wandb_version: 1

_content:
  desc: null
  value:
    model: '{''embed_dim'': 768, ''out_dim'': 2, ''drop_p'': 0.5, ''bert_version'':
      ''bert-base-uncased'', ''max_len'': 512}'
    pred: '{''path_data'': ''./data/external/example.txt'', ''device'': ''cpu''}'
    train: '{''batch_size'': 64, ''epochs'': 10, ''learning_rate'': 1e-05, ''path_train_set'':
      ''data/processed/train.csv'', ''path_test_set'': ''data/processed/test.csv'',
      ''device'': ''cpu'', ''seed'': 42}'
_flags_cache:
  desc: null
  value:
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2023-01-16'', (''%H-%M-%S'',): ''19-20-31''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1673893234.585129
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.13.9
      6: 4.24.0
      8:
      - 5
