wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1673886282.149496
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      3:
      - 23
      4: 3.10.4
      5: 0.13.9
      6: 4.24.0
      8:
      - 5
