hyperparameters:
    train_batch_size: 8
    valid_batch_size: 4
    epochs: 1
    learning_rate: 1e-05
#    data_path: "data/processed/train.csv"
    #hidden_layers: 768
    #output_size: 2
    #drop_p: 0.5