hyperparameters:
    train_batch_size: 64
    valid_batch_size: 64
    epochs: 10
    learning_rate: 1e-05
    path_train: "data/processed/train.csv"
    path_test: "data/processed/test.csv"
    device: "cpu"