wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673611794.373294
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 55
      2:
      - 1
      - 11
      - 49
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.8
      6: 4.25.1
      8:
      - 5
batch_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 1.0e-05
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0.001
workers:
  desc: null
  value: 0
