# Hyperparameters for training the model
batch_size: 64
epochs: 30
learning_rate: 1e-04
path_train_set: "data/processed/train.csv"
path_test_set: "data/processed/test.csv"
path_train_set_cloud: "gs://bucket-train-bert/data/processed/train.csv"
path_test_set_cloud: "gs://bucket-train-bert/data/processed/test.csv"
seed: 42

gpu_override: 1  # DO NOT CHANGE THIS!!!